<a href="https://colab.research.google.com/github/shilongjaycui/mathematical-programming/blob/main/solving_linear_systems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1

In [ ]:
import numpy as np

M = []
i = int
j = int

def row_swap(M, i, j):
  '''Takes as input a matrix object M and two indices i and j of a row and a column respectively.
     If the entry M[i,j] != 0, the function returns the matrix M unaltered.
     Otherwise the function steps through the entries M[k,j] of the j-th column with k ≥ i.
     If it finds an entry M[k,j] != 0, the function swaps the i-th and k-th rows.
     If there is no such entry M[k,j] != 0, return the original matrix M unaltered.'''
  matrix = M.copy() #list = [], list2 = list.copy()
  if M[i,j] == 0: #it's M[i,j], not M[i][j]
    k = i
    while k < len(M):
      if M[k,j] != 0:
        v = M[i].copy()
        matrix[i] = M[k]
        matrix[k] = v
        return matrix
      else:
        k += 1
    return M #has to return something, otherwise nothing will come out if it didn't go through the if-statement
  else:
    return M

A = np.matrix([[1,2],[3,4]])
B = np.matrix([[0,2],[3,4],[5,6]])
C = np.matrix([[1,2,3],[0,0,6],[0,8,9]])

print(row_swap(A, 0, 0))
print(row_swap(B, 0, 0))
print(row_swap(C, 1, 1))

[[1 2]
 [3 4]]
[[3 4]
 [0 2]
 [5 6]]
[[1 2 3]
 [0 8 9]
 [0 0 6]]


Problem 2

In [ ]:
M = []
i = int
j = int

def row_add(M, i, j):
  '''Takes as input a matrix object M and two indices i and j of a row and a column respectively.
     If the entry M[i,j] != 0, the function iterates through the rows M[k] of M with index k > i.
     At each step, replace the row M[k] with the row M[i,j] ∗ M[k] − M[k,j] ∗ M[i].
     Otherwise, return the original matrix A unaltered.'''
  matrix = M.copy()
  if M[i,j] != 0:
    k = i + 1
    while k < len(M):
      if M[k,j] != 0: #check if it's not equal to zero
        matrix[k] = M[i,j]*M[k] - M[k,j]*M[i]
      k += 1
    return matrix
  else:
    return M

A = np.matrix([[1,2],[3,4]])
B = np.matrix([[3,4],[0,2],[5,6]])
C = np.matrix([[1,2,3],[0,5,6],[0,8,9]])

print(row_add(A, 0, 0))
print(row_add(B, 0, 0))
print(row_add(C, 1, 1))

[[ 1  2]
 [ 0 -2]]
[[ 3  4]
 [ 0  2]
 [ 0 -2]]
[[ 1  2  3]
 [ 0  5  6]
 [ 0  0 -3]]


Problem 3

In [ ]:
M = []

def ref(M):
  '''Takes as input a matrix object M and reduces the matrix to echelon form.'''
  i = 0
  j = 0
  while i < M.shape[0] and j < M.shape[1]: #use while-loop rather than for-loop
    M = row_swap(M, i, j) #SET M EQUAL TO WHAT YOU'VE ROW SWAPPED
    if M[i,j] == 0:
      j += 1
    else:
      M = row_add(M, i, j) #SET M EQUAL TO WHAT YOU'VE ROW SWAPPED
      i += 1
      j += 1
  return M

A = np.matrix([[1,2],[3,4]])
print(ref(A))
B = np.matrix([[0,2],[3,4],[5,6]])
print(ref(B))
C = np.matrix([[1,2,3],[0,0,6],[0,8,9]])
print(ref(C))

[[ 1  2]
 [ 0 -2]]
[[3 4]
 [0 2]
 [0 0]]
[[1 2 3]
 [0 8 9]
 [0 0 6]]
